name: weather_app
description: A modern weather application built with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # データベース関連
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # HTTP通信とデータ処理
  http: ^1.1.0
  intl: ^0.18.1
  
  # 位置情報関連
  location: ^5.0.3
  geolocator: ^10.1.0
  
  # Firebase関連
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  
  # UI関連
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/sun.png
    - assets/rain.png
    - assets/sanderrain.png
    - assets/mistrain.png
    - assets/cloud.png
    - assets/smork.png
    - assets/mist.png
    - assets/snow.png
    - assets/tatumaki.png
    - assets/harekumori.png
    - assets/kumorihare.png
    - assets/backrain.jpg
    - assets/cloud1.png
    - assets/cloud1.jpg
    - assets/icon/yama_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/yama_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/yama_logo.png"
